/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#3f4a3f",
        "surface-container-low": "#171d17",
        "primary-container": "#3da35d",
        "surface-container-lowest": "#0a100a",
        "on-secondary-fixed-variant": "#1e502e",
        "inverse-on-surface": "#2c322b",
        "surface-container": "#1b211b",
        "surface-variant": "#30362f",
        "surface-container-highest": "#30362f",
        "inverse-primary": "#006d33",
        "primary-fixed": "#92f8a9",
        "on-surface-variant": "#becabc",
        "tertiary-fixed-dim": "#89ceff",
        "on-surface": "#dee4da",
        "surface-tint": "#76db8f",
        "tertiary-fixed": "#c9e6ff",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#001e2f",
        "on-background": "#dee4da",
        "on-tertiary-fixed-variant": "#004c6e",
        "error-container": "#93000a",
        "secondary-container": "#205331",
        "primary-fixed-dim": "#76db8f",
        "on-secondary-container": "#8fc599",
        "on-primary-container": "#003114",
        "tertiary": "#89ceff",
        "surface-bright": "#343b34",
        "secondary": "#9dd3a7",
        "on-primary-fixed": "#00210b",
        "on-tertiary": "#00344d",
        "on-primary": "#003918",
        "secondary-fixed": "#b8f0c2",
        "background": "#0f150f",
        "outline": "#889487",
        "tertiary-container": "#009ada",
        "primary": "#76db8f",
        "on-tertiary-container": "#002d43",
        "surface-container-high": "#252c25",
        "surface-dim": "#0f150f",
        "on-error": "#690005",
        "inverse-surface": "#dee4da",
        "surface": "#0f150f",
        "on-secondary-fixed": "#00210c",
        "on-primary-fixed-variant": "#005225",
        "on-secondary": "#01391a",
        "secondary-fixed-dim": "#9dd3a7",
        "error": "#ffb4ab"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "card-gap": "20px",
        "container-padding": "24px",
        "unit": "4px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "mono-data": ["monospace"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
